// Generated by CoffeeScript 2.7.0
  // stores.coffee

// import {PrefsDataStore} from '$lib/browserStores.js'
import {
  PrefsDataStore
} from '@jdeighan/svelte-utils/stores';

export var lAllowedKeys = ['firstName', 'lastName', 'address', 'phone', 'email', 'bgColor'];

export var hPrefs = new PrefsDataStore({
  firstName: 'John',
  lastName: 'Deighan'
});
