// Generated by CoffeeScript 2.7.0
import adapter from '@sveltejs/adapter-static';

import {
  mdsvex
} from 'mdsvex';

import {
  coffeePreProcessor
} from '@jdeighan/svelte-utils/preprocessors';

export default {
  kit: {
    adapter: adapter()
  },
  extensions: ['.svelte', '.md'],
  preprocess: [
    //		sveltePreprocess()
    mdsvex({
      extensions: ['.md']
    }),
    {
      script: coffeePreProcessor
    }
  ]
};
